services:
  - type: web
    name: omniload
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: YT_COOKIES
        sync: false
      - key: YT_PROXY
        sync: false
